update code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,107 +1,147 @@
-# Java Maven CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-java/ for more details
-#
 version: 2
 jobs:
-  checkout_code: # job1
+  build:
     docker:
-      - image: circleci/openjdk:8-jdk
-    working_directory: ~/circleci-demo-workflows
+      - image: circleci/openjdk:8-jdk-browsers
+    working_directory: ~/repo
     steps:
       - checkout
-      # Lưu thư file, thư mục để sử dụng ở job khác trong workflows
-      - persist_to_workspace:
-          root: /home/circleci
-          paths: circleci-demo-workflows/*
-
-  get_dependencies: # job2
-    docker:
-      - image: circleci/openjdk:8-jdk
-    working_directory: ~/circleci-demo-workflows
-    steps:
-      # Lấy lại file đã lưu ở job1
-      - attach_workspace:
-          at: ~/
       - restore_cache:
-          keys:
-          - cricle-test-{{ checksum "pom.xml" }}
-          # fallback to using the latest cache if no exact match is found
-          - cricle-test-
+          key: circleci-challenge-{{ checksum "pom.xml" }}
+
       - run: mvn dependency:go-offline
+
       - save_cache:
           paths:
-            - ~/.m2
-          key: cricle-test-{{ checksum "pom.xml" }}
+           - ~/.m2
+          key: circleci-challenge-{{ checksum "pom.xml" }}
 
-  build: # job3
-    docker:
-      - image: circleci/openjdk:8-jdk
-    working_directory: ~/circleci-demo-workflows
-    environment:
-      MAVEN_OPTS: -Xmx3200m
-    steps:
-      # Lấy lại file đã lưu ở job1
-      - attach_workspace:
-          at: ~/
-      - run: mvn compile
+      - run:
+          name: Start SauceLabs Tunnel (required if testing on CircleCI container)
+          command: |
+            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
+            tar -xzf saucelabs.tar.gz
+            cd sc-*
+            # startup saucelabs tunnel as background task (its a blocking command)
+            bin/sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} &
+            #wait for sauce tunnel up to 1 minute
+            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
 
-  test: #job4
-    docker:
-      - image: circleci/openjdk:8-jdk
-    environment:
-      MAVEN_OPTS: -Xmx3200m
-    working_directory: ~/circleci-demo-workflows
-    steps:
-      # Lấy lại file đã lưu ở job1
-      - attach_workspace:
-          at: ~/
-      # run tests!
-      - run: |
-          mvn integration-test
-          mkdir target/junit
+      - run:
+          name: Build and test
+          command: |
+            mvn package -B  #run your tests
+            killall sc #kill saucelabs tunnel
+
+      - run:
+          name: Copy deployment artifacts to workspace
+          command: |
+            cp target/circleci-challenge-*.jar /tmp/standalone-app.jar
+            cp .circleci/setup-heroku.sh /tmp/setup-heroku.sh
+            cp src/main/resources/deployment/cf-dev-manifest.yml /tmp/
+
       - store_test_results:
-          path: target/junit
+          path: target/surefire-reports
 
-  deploy:
+      - store_artifacts:
+          path: /tmp/standalone-app.jar
+      - store_artifacts:
+          path: /tmp/cf-dev-manifest.yml
+
+      - persist_to_workspace:
+                root: /tmp
+                paths:
+                  - standalone-app.jar
+                  - setup-heroku.sh
+                  - cf-dev-manifest.yml
+
+  deploy-heroku:
     docker:
-      - image: circleci/openjdk:8-jdk
-    working_directory: ~/circleci-demo-workflows
+      - image: circleci/openjdk:8-jdk-browsers
+    working_directory: ~/deploy
     steps:
+      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
       - attach_workspace:
-          at: ~/
+          at: /tmp
+
       - run:
           name: Run setup script
-          command: bash .circleci/setup-heroku.sh
-      - add_ssh_keys:
-          fingerprints:
-            - "a1:5d:48:05:92:d2:b4:82:87:41:46:b0:8c:29:3b:46"
+          command: bash /tmp/setup-heroku.sh
+
       - run:
-          name: Deploy Master to Heroku
+          name: Heroku Deploy
           command: |
-            git push --force git@heroku.com:fathomless-inlet-82408.git HEAD:refs/heads/master
-            heroku run python manage.py deploy
-            heroku restart
+            cp /tmp/standalone-app.jar .
+            ls -la
+            heroku plugins:install heroku-cli-deploy
+            heroku plugins:install heroku-cli-deploy  # when debugging on circle image, first run succeeded, but did not make plugin available
+            heroku deploy:jar standalone-app.jar --app floating-stream-79370
+      - run:
+          name: Smoke Test
+          command: |
+            # Heroku deploy command will pass even if application crashes. Simple smoke test to make sure app is up.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://floating-stream-79370.herokuapp.com`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
+
+
+  deploy-cf:
+    docker:
+      - image: eddiewebb/queue-circleci-openjdk:8-jdk-browsers
+      #- image: circleci/openjdk:8-jdk-browsers
+    working_directory: ~/deploy
+    steps:
+      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
+      - attach_workspace:
+          at: /tmp
+
+      - run: queueBuildUntilFrontOfLine 5 #do not run parallel deployments
+      - run:
+          name: Setup CF CLI
+          command: |
+            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
+            sudo dpkg -i cf-cli_amd64.deb
+            cf -v
+            cf api https://api.run.pivotal.io
+            cf auth $CF_USER $CF_PASSWORD
+            cf target -o eddies-org -s development
+
+      - run:
+          name: CF Deploy
+          command: |
+            # Copy deployable jar and CF Manifest to current dir
+            cp /tmp/standalone-app.jar .
+            cp /tmp/cf-dev-manifest.yml .
+            # Push as "dark" instance
+            cf push circleci-dark -f cf-dev-manifest.yml -p standalone-app.jar -n circleci-dark
+            # Verify new version is working on dark URL.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://circleci-dark.cfapps.io/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "dark route note available, failing deploy"
+              exit 1
+            fi
+            # Send "real" url to new version
+            cf map-route circleci-dark cfapps.io -n circleci-challenge
+            # Stop sending traffic to previous version
+            cf unmap-route circleci-challenge cfapps.io -n circleci-challenge
+            # stop previous version
+            cf stop circleci-challenge
+            # delete previous version
+            cf delete circleci-challenge -f
+            # Switch name of "dark" version to claim correct name
+            cf rename circleci-dark circleci-challenge
+
 
 workflows:
   version: 2
-  build_and_test:
+  build-deploy:
     jobs:
-      - checkout_code
-      - get_dependencies: # get_dependencies chạy sau checkout_code
-          requires:
-            - checkout_code
-      - build: # xong get_dependencies mới build
-          requires:
-            - get_dependencies
-      - test: # xong get_dependencies mới test
-          requires:
-            - get_dependencies
-      - deploy:
-          type: approval
+      - build
+      - deploy-heroku:
           requires:
             - build
-            - test
-          filters:
-            branches:
-              only: master
+      - deploy-cf:
+          requires:
+            - build
